version: '3.7'

services:

  nginx:
    container_name: zekawebapp
    image: zekawebapp
    build:
      context: .
      dockerfile: angular.prod.dockerfile
    ports:
      - "4200:80"
    environment:
      - API_BASE_URL=http://localhost:9010
