version: '3.7'

services:

  zeka:
    container_name: zeka-webapp
    image: zeka-webapp
    ports:
      - "4200:80"
    environment:
      - API_BASE_URL=http://isp-web-api:5002
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    external: true
